name=PicoSem
version=1.0.1
author=IWILZ
maintainer=IWILZ <llavezzaro@gmail.com>
sentence=Dual-core semaphore library for RP2040
paragraph=Simple semaphore library to synchronize the exchange of data between the 2 cores of a Raspberry Pi Pico under Arduino IDE framework
category=Communication
url=https://github.com/IWILZ/PicoSem
architectures=rp2040
